FROM nginx:alpine


COPY index.html /usr/share/nginx/html/
COPY scripts1.js /usr/share/nginx/html/
COPY styles.css /usr/share/nginx/html/
COPY usuario.html /usr/share/nginx/html/
COPY scripts2.js /usr/share/nginx/html/
COPY mensajes.html /usr/share/nginx/html/
COPY scripts3.js /usr/share/nginx/html/
COPY notificaciones.html /usr/share/nginx/html/
COPY scripts4.js /usr/share/nginx/html/

